### ISSUE TITLE
[feature] Re-evaluate if we need to record the GH context in setup-token Action

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1410]

**Comment by ianlewis** [comment]
I think we can probably drop it. We should probably white list what we include anyway since we probably don't want to carry any potentially sensitive fields.

**Comment by laurentsimon** [comment]
if we want to support branches for verifier, we'll need to port the logic from the verifier to here. We could also start without branch support for the first release.

**Comment by asraa** [comment]
I thought this was for the token - not for the predicate.

**Comment by laurentsimon** [comment]
+1, I confused the two features. Is recording sensitive fields riskier in the token or the provenance, or same? :)

**Comment by asraa** [comment]
I think it's the same - they're both posted to Rekor and somewhat public.

So right now we pick and choose the env fields, and record the entire event payload. This gives us branch support, btw.

We can redact more of the event payload, since the only fields we really need for branch support are the base ref, trigger_committish and maybe 1 more of the event payload.

The sensitive info parts are inside larger structs (repository -> owner) of the event payload.

**Comment by laurentsimon** [comment]
that brings up another question: what do we do with sensitive fields that are necessary inputs in the token https://github.com/slsa-framework/slsa-github-generator/issues/1575?

I forgot that they are recorded in the token too. The masking I proposed just masks them from the final provenance, but not the token.

Does rekor always record the plaintext? Or it depends on the type of record / input (attestation vs blob vs ...)?

**Comment by asraa** [comment]
> Does rekor always record the plaintext? Or it depends on the type of record / input (attestation vs blob vs ...)?

For simple signing a blob, it does not, but the attestation content will be there. So I suppose the token is actually in a better state!

**Comment by laurentsimon** [comment]
ah, great, Then no need to prioritize it. btw, where can I learn which types have their plaintext recorded?
