### ISSUE TITLE
Add pre-submit and/or e2e tests for docker-builder

### ISSUE THREAD

**Issue by rbehjati** [slsa-framework/slsa-github-generator#1479]
_Originally posted by @ianlewis in https://github.com/slsa-framework/slsa-github-generator/issues/1388#issuecomment-1373595495_

**Comment by asraa** [comment]
For e2e, can we lump in with the presubmit for the entire workflow?

https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/pre-submit.e2e.docker-based.default.yml

I can start a PR to update the workflow so that we actually compile the builder binary and use it's buildDefinition!

**Comment by rbehjati** [comment]
I think it is a great idea, if it is possible to do :)

**Comment by asraa** [comment]
When https://github.com/slsa-framework/slsa-github-generator/pull/1485 is merged, I will move over e2e tests into example-package. We should test

* multiple subjects in the output path (output folder vs output file). do no subject produced in the output folder cause a failure?
* the different push events (workflow dispatch, tag, release)
* compile-builder vs not
* pull_request events on this repo produce unsigned attestations

**Comment by asraa** [comment]
These are all done now. pre-submits with unsigned are in this repo, events are in example-package with multiple artifacts.
