### ISSUE TITLE
[cleanup] [byo] Can the slsa-token be a slsa predicate?

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#1480]
**Is your feature request related to a problem? Please describe.**
This is something I was trying to think about as I was updating https://github.com/slsa-framework/slsa-github-generator/pull/1477

The SLSA token should contain all the inputs needed to execute the tool, and this information should be the information in the signed predicate as well.

I was wondering if this could in effect just be a SLSA predicate. Note that the caller workflow would be signing the predicate in the `setup-token` action, and after the SRW verifies it, the SRW would then use this, augment with the additional context (from the reusable workflow) to sign in the output provenance.

Right now, the predicate I have in https://github.com/slsa-framework/slsa-github-generator/pull/1477 doesn't include the build action path or the builder info (private_repository, runner, audience) though. But that is trivial to add in buildconfig.

The reason for this is just simplifying the format for the SLSA token.

@laurentsimon

**Comment by laurentsimon** [comment]
Do we still plan on doing this? IIUC, verifying every bit of the token is more-or-less the same amount of work as re-creating it ourselves. Keeping both separate also helps us:
1. Have a level of indirection to change things under the hood
2. No need to verify every field of the token, since we cherry-pick what to copy from the token into the predicate.

I'm tempted to closed this. @asraa wdut?

**Comment by asraa** [comment]
Agree - let's close this one. I don't think we want to keep them the same because the meanings of the environment are also different (e.g. the GITHUB_JOB doesn't reference the trusted SLSA 3 builders GITHUB_JOB)
