### ISSUE TITLE
[feature][docker] Add a flag for skipping `build` for `pull_request` events

### ISSUE THREAD

**Issue by rbehjati** [slsa-framework/slsa-github-generator#1774]
**Is your feature request related to a problem? Please describe.**
We want to run the Docker-based workflow on pull-request events, to make sure the workflow is setup correctly, but the build process is computationally heavy and time consuming, so we want to skip that for pull request events. 

**Describe the solution you'd like**
Add a `dry-run` flag (i.e., workflow input) that, if set to true, skips the `build` and `provenance-generation` steps, and only generates a `BuildDefinition`. By default the `dry-run` flag is set to false.

We should clarify that the workflow outputs will be empty if `dry-run` is set to true.

**Describe alternatives you've considered**
1. We could consider adding a `dry-run-on-pull-request` flag, and internally apply the `dry-run` logic only on `pull_request` events. But I believe that makes the workflow too complicated. 
2. Instead of skipping the `build` step, we could extend the build config with a new `dry-run-command` field, and run that instead of  the `command` when the `dry-run` flag is set to true. This adds extra work and overhead to maintainers of the source repo who should provide the build config, and can cause confusion. (e.g., a `dry-run-artifacts-path` might be needed too) 

**Additional context**
N/A

CC: @asraa

**Comment by asraa** [comment]
> We should clarify that the workflow outputs will be empty if dry-run is set to true.

+1

In the case where we do not have signing available, we output the unsigned SLSA attestation to the slsa outputs folder. We could consider uploading the build-definition there too? All outputs in the slsa outputs folder have different extensions:
* .intoto.sigstore for the signed attestations
* .intoto for the unsigned attestations when no token is detected
* .json for the build definition

OR, we can just leave omit it from the slsa outputs, since the user may not care about an incomplete provenance.

**Comment by rbehjati** [comment]
After thinking more about this and a discussion with @tiziano88 I've decided it is better to enable/disable runs on pull_request events using a label. I believe this is sufficiently flexible, without introducing any additional complexity, or variation in behavior. So I am closing this issue. Feel free to reopen if you think there are other use cases where a dry-run option could be beneficial.
