### ISSUE TITLE
[bug] Don't validate or read event_path from slsa-token

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1900]
We're validating and reading the event_path from the token (https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/actions/verify-token/src/predicate1.ts#L121). I'm not sure there is guarantee that the re-usable workflow's runner's path is identical to the caller's.

I think we need to remove the validation that slsa-token.event_path == GITHUB_EVENT_PATH and always read from GITHUB_EVENT_PATH.

**Comment by ianlewis** [comment]
Yeah, fair enough. Having the EVENT_PATH on the token is probably useless really.

**Comment by ianlewis** [comment]
I think it might be useful to include something like a hash checksum of the event payload so that we can verify that it's the same between `setup-token` and `verify-token` though.

We could calculate the hash in `setup-token` and include it in the token. In `verify-token` we can read the event payload again and verify that the hash is the same. That way we are sure that the event payloads are the same.

**Comment by laurentsimon** [comment]
Not sure this works. The event payload is different across runners, and I think between a re-usable workflow and normal workflow some data is also updated.

**Comment by ianlewis** [comment]
Yeah, I'll test this a bit more. I wonder if we shouldn't just remove the full payload in the provenance and just include relevant fields that we can verify individually?
