### ISSUE TITLE
[feature][byob] SRW should upload to release assets

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#2062]
See https://github.com/slsa-framework/slsa-github-generator/issues/2035#issuecomment-1522333451

Based on the TRW's input (setup-token Action)

/cc @aalmiray

**Comment by ianlewis** [comment]
We have a number of TODOs in the code pointing to #1575 relating to masking data in provenance. For v1.0 provenance we currently include the entire event object which is problematic.

**Comment by laurentsimon** [comment]
Because permissions in reusable workflow are currently not dynamic, a caller needs to provide the union of all possible permissions. So until GitHub fixes this, we may instead provide an Action for TRWs to call to perform the upload. This still leaves TRWs with the broader set of permissions, though.

**Comment by ianlewis** [comment]
> Because permissions in reusable workflow are currently not dynamic, a caller needs to provide the union of all possible permissions. So until GitHub fixes this, we may instead provide an Action for TRWs to call to perform the upload. This still leaves TRWs with the broader set of permissions, though.
> 
> Another option is to provide multiple delegator SRWs

I think tools like goreleaser and jreleaser will do the uploads themselves but not all will so I think we may need to provide a couple of different delegator SRWs that request different permissions. It's a bit unfortunate though since I think the only real difference between them would be which permissions they request.

**Comment by aalmiray** [comment]
> I think tools like goreleaser and jreleaser will do the uploads themselves but not all will so I think we may need to provide a couple of different delegator SRWs that request different permissions. It's a bit unfortunate though since I think the only real difference between them would be which permissions they request.

This is correct at least for originally configured release assets (such as Zips and Tars). However, this issue is related to the attestation file created by the SRW which seats outside of goreleaser/jreleaser's control.

There are a few options:

- SRW uploads attestation file(s) to the given Git release. Requires tweaking permissions as @laurentsimon explained.
- TRW uploads attestation files(s). This requires passing the file(s) from SRW to TRW (1), TRW uploads the file(s) by updating an existing Git release (2)

1. Requires uploading files with `actions/upload-artifact` to a given bucket that both SRW and TRW agree beforehand.
2. TRW uses `actions/download-artifact` to pull down the attestation file(s) and figures out a way to upload the Git release.

**Comment by laurentsimon** [comment]
> There are a few options:
> 
> * SRW uploads attestation file(s) to the given Git release. Requires tweaking permissions as @laurentsimon explained.
> * TRW uploads attestation files(s). This requires passing the file(s) from SRW to TRW (1), TRW uploads the file(s) by updating an existing Git release (2)
> 
> 1. Requires uploading files with `actions/upload-artifact` to a given bucket that both SRW and TRW agree beforehand.
> 2. TRW uses `actions/download-artifact` to pull down the attestation file(s) and figures out a way to upload the Git release.

@ianlewis is working on this. The SRW already uploads the attestations, and provide the name as output to download them. See https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/delegator_generic_slsa3.yml#L63-L77

We will provide an Action to help download. The reason for this is that artifacts uploaded *may* be altered by other parts of the workflows, including the PW. So we need to ensure the TRW downloads the right attestations, and this is why the SRW also outputs the sha256 of the attestations. Here is the Action aimed at PW, ie end-users for nodejs builder https://github.com/slsa-framework/slsa-github-generator/tree/main/actions/nodejs/secure-attestations-download. Ian will create a similar Action (probably called delegator/secure-download-attestations) for TRW authors. We imagine it would be used as follows:
1. Download the attestation
2. Verify the artifacts using the downloaded attestation using slsa-verifier
3. Do what you want with binaries or attestations.

Wdut?

**Comment by aalmiray** [comment]
Makes sense to me. If for some reason the SRW can't upload the attestations to a given Github release then if befalls into the TRW to do so. This of course makes sense for BYOB TRWs.

If a PW invokes the generic SRW directly then the PW would be responsible for download, verification, and upload.

**Comment by laurentsimon** [comment]
A PW won't be able to use a SRW directly, at least that's not the intended use case (today the call will fail because we expect a re-usable workflow because we set the builder.id to the TRW in the provenance). 
The use case we have in mind: if there is something the PW wants to do with the attestations that the TRW does not do itself - maybe, upload the attestation somewhere - the it can still do it.

**Comment by laurentsimon** [comment]
So we have this nodejs Action https://github.com/slsa-framework/slsa-github-generator/blob/main/actions/nodejs/secure-attestations-download/action.yml which is ready to use (You can see an example in https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/nodejs#getting-started). At a high-level, we upload a tarball and the Action both downloads and untars it. 

I've sent a PR to have the same Action for the delegator https://github.com/slsa-framework/slsa-github-generator/pull/2136.


@aalmiray Can you verify it solves the issue?

**Comment by aalmiray** [comment]
I suppose the TRW will use the secure-download-action to get files created by the SRW, to use then in any way it deems necessary, OK. 

However, the question remains: does the SRW upload attestation files to a Git release page given a particular tag as parameter? This would be an optional step as a TRW may opt to upload the attestation to a different location.

**Comment by laurentsimon** [comment]
> However, the question remains: does the SRW upload attestation files to a Git release page given a particular tag as parameter? This would be an optional step as a TRW may opt to upload the attestation to a different location.

SRW won't upload:
1. The callback Action is responsible for uploading built artifacts where it wants
2. The TRW can use the secure-download-action to download the attestations and upload them to whichever location it wants, including to GH release assets, or to a registry. TRW may decide to not upload anything as part of the callback Action, and instead do everything within the TRW: download bot 1) the attestations and 2) the artifacts. We may expose a public `secure-upload-artifact` to the callback Action for this. We already use an internal Action (https://github.com/slsa-framework/slsa-github-generator/tree/main/.github/actions/secure-upload-folder which we use for uploading attestations https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/delegator_generic_slsa3.yml#L284) and we have plans to make it public under `actions/...` (nobody asked for it yet so we have not made it public but we're happy to do that)

Does this answer your question? Or did I mis-understand? Would this resolve the problem?

**Comment by aalmiray** [comment]
I understand that the TRW will have the capability to upload secure downloaded files generated by the SRW. It's just that the generic SLSA generator has the option to upload git release assets while the SRW delegates that behavior to TRWs. 

This means there will be repetition among TRWs to perform attestation upload as git release assets. 

If this is the intended design between SRW and TRWs for BYOB then I guess I'll abide by the rules 😅

**Comment by laurentsimon** [comment]
> I understand that the TRW will have the capability to upload secure downloaded files generated by the SRW. It's just that the generic SLSA generator has the option to upload git release assets while the SRW delegates that behavior to TRWs.

I see what you mean now. The generic generator is different from the generic delegator (SRW) that the TRW calls. The SRW will be https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/delegator_generic_slsa3.yml, and does not upload anything based on tags. So there will be no repetition.

Let me know if this clarifies things.
 
> If this is the intended design between SRW and TRWs for BYOB then I guess I'll abide by the rules 😅

We want to be sure the design works. No rules to abide by :-) If something seems wrong, we can fix it. Appreciate all the questions and feedback.

**Comment by aalmiray** [comment]
Thanks 😅

I understand the difference between generic delegator and generator. SRWs rely on the former, while the latter provides the optional behavior (upload attestation file to git release) I'm looking for. 

TRWs have the option to securely download files created by the SRW and upload them to wherever they deem necessary. If one of such upload places turns out to be a git release so be it. Which also happens to be a place that the generic generator may upload things to, which may also be a common trait shared by several TRWs. Hence why I thought it would be a good idea to provide it as an optional step in the SRW delegator.

**Comment by ianlewis** [comment]
> TRWs have the option to securely download files created by the SRW and upload them to wherever they deem necessary. If one of such upload places turns out to be a git release so be it. Which also happens to be a place that the generic generator may upload things to, which may also be a common trait shared by several TRWs. Hence why I thought it would be a good idea to provide it as an optional step in the SRW delegator.

For the types of projects that release to GitHub releases there could be some duplication but would it be much more than a couple calls to GH actions (`actions/download-artifact` and `softprops/action-gh-release`)? For others, like Node or container image projects, I think this would be largely unnecessary since most projects don't release to GitHub releases.

Because GHA requires users to grant all permissions that could ever be needed to a reusable workflow, not just the permissions that will actually be needed (https://github.com/slsa-framework/slsa-github-generator/issues/2076) we got a lot of feedback asking us to not require those permissions and to make the reusable workflows/actions we provide more modular (i.e. each reusable workflow and action does fewer things and are composable rather than having functionality triggered via input flags). This seems to be what GHA seems to encourage with its workflow and permissions model.

Given that the publishing location is tool/ecosystem-specific I think it probably still makes the most sense for it to be in the TRW, though we could potentially provide an action to make it easier for TRWs to implement.

**Comment by laurentsimon** [comment]
Closing this since I think it's been resolved. Please re-open if you think I've made a mistake
