### ISSUE TITLE
[bug] Schedule action pre-submit tests fail due to missing badges

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#2238]
Schedule actions in this repo re-use the report success script from example-package. They fail because of the new badge logic in the script: https://github.com/slsa-framework/slsa-github-generator/actions/runs/5195861218/jobs/9368998750

cc @ianlewis

**Comment by asraa** [comment]
And in slsa-verifier: https://github.com/slsa-framework/slsa-verifier/actions/runs/5195266465/jobs/9367891708

**Comment by ianlewis** [comment]
I reverted this and made it so they are only updated in the `example-package` repo. These workflows should run successfully now.

**Comment by ianlewis** [comment]
detect-workflow-js: https://github.com/slsa-framework/slsa-github-generator/actions/runs/5206121066

slsa-verifier: I can't trigger it via workflow_dispatch because of a bug in the workflow. Fix: https://github.com/slsa-framework/slsa-verifier/pull/637. It should be ok the next time it is scheduled to run though.

**Comment by ianlewis** [comment]
The slsa-verifier test is also passing now: https://github.com/slsa-framework/slsa-verifier/actions/runs/5206658289
