### ISSUE TITLE
[feature] Validate the targets inputs

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#2308]
If we require the targets be referenced from the workspace root this might fail (or even succeed) in some unexpected ways if users don't do that. For example, if there is a `a/b/c:main` target and a `abc:main` target this would turn `a/b/c:main` into `abc:main` and upload a different target than was intended.

Maybe we should validate it and throw an error if the target doesn't begin with `//`? Maybe also validate that the target id is specified? e.g. check for the `:`?

See: https://github.com/slsa-framework/slsa-github-generator/pull/2267#discussion_r1234513829

// @enteraga6

**Comment by enteraga6** [comment]
Target parsing to get artifact output path through bash is no longer a part of the Bazel Builder. Now the logic to get the artifacts is done through `bazel cquery` and `bazel query`, added in #2324 and #2362, which includes generic glob patterns that bazel accepts such as `//src/...` or `//src/internal:all`. This makes validation of `:` unneeded.

I agree that validation of `//` should be added as well, and will include it soon. Despite that technically, the Bazel Builder could build targets without `//`, they would still have to be referenced from the root since that is where the build command takes place in. I think that adding this constraint and validation on the targets will guide users on using the Bazel Builder properly (meaning inputting their target paths from the root), despite losing functionality over the edge case of a user that wants to reference their targets from the root but not put `//` in front of targets.

Do you agree? 

// @ianlewis

**Comment by ianlewis** [comment]
Yeah, I'm fine with allowing relative build targets as long as they are built from the project root directory. Though I do wonder about projects that might have the bazel workspace in a subdirectory. We might want to consider allowing the user to specify a directory to run the build in, similar to the Node.js builder's [`directory` input](https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/nodejs#workflow-inputs). We can do that later though.

For now, I think we would just need to make it so that if a user does put in a relative path it's either built properly or an error message is produced. I think the original code just blindly assumed the first two `/` characters were at the beginning of the build target.

**Comment by enteraga6** [comment]
Yes that is right. A bash script parsed it before with the assumption of the `//`.

Using `bazel query` and `bazel cquery`, if a user puts in a relative path for a target that is not referenced from the root, the following error message is outputted:

```
ERROR: no such package 'internal': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/runner/work/slsa-lvl3-generic-provenance-with-bazel-example/slsa-lvl3-generic-provenance-with-bazel-example/internal
 ```
 
 This was for an input that was `internal:target` instead of `src/internal:target` or `//src/internal:target`, which would have built correctly. Thus, those commands handle the validation for us and provides an error message when target is unreachable. Or do you think we should strengthen it ourselves with explicit mention of root (or in the future subdirectory)?
 
 I agree to adding directory input to build inside sub-directories! Tracking issue here: #2393
