### ISSUE TITLE
v1.1.0 fails with `error searching rekor entries: no matching entries found`

### ISSUE THREAD

**Issue by chipzoller** [slsa-framework/slsa-github-generator#327]
I happened to see the v1.1.0 pre-release and bumped my (WIP) action to pin to that digest, but I see it fails in the builder step with `error searching rekor entries: no matching entries found` [here](https://github.com/chipzoller/zulu/runs/6918142238?check_suite_focus=true#step:4:52).

**Comment by asraa** [comment]
my guess on what's going on, rekor isn't indexing the subject digest because it exits early here because it hasn't populated the Content of the entry yet (an internal rekor bug)
https://github.com/sigstore/rekor/blob/3708c5c8e3321b024e8aeb83f9fc00af47665c0b/pkg/types/intoto/v0.0.1/entry.go#L83-L84

FWIW I can't index the entry by the payload hash earlier, but that's uncanonicalized and I can't find what that *would* be.

At the next cut of Rekor we will continue to index the Subject Digests, which is what the verifier relies on
https://github.com/sigstore/rekor/blob/4f0b750ea3cee548684227570190250fcd136f02/pkg/types/intoto/v0.0.1/entry.go#L87-L95

**Comment by laurentsimon** [comment]
@[chipzoller](https://github.com/chipzoller), fyi this is a rekor/sigstore issue, not something we can fix on our repository. Could you creat an issue in the rekor repo?

**Comment by chipzoller** [comment]
It works on v1.0.0 of the same action when I reverted. It seems like since this logic is encapsulated in slsa-github-generator, it would be more appropriate for you all to create and track the issue against Rekor.

**Comment by asraa** [comment]
https://github.com/sigstore/rekor/issues/876 
https://github.com/sigstore/rekor/issues/872

it is here! thank you again!

**Comment by asraa** [comment]
https://github.com/slsa-framework/slsa-github-generator/pull/330

in conjunction with 
https://github.com/slsa-framework/slsa-verifier/pull/97

will fix the issue!

**Comment by ianlewis** [comment]
The fixes @asraa pointed to are in and I believe this is working now (based our closed e2e tests). Thanks for the report!
