### ISSUE TITLE
[bug] blocking pre-submit are not blocking

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#522]
I think we have the wrong list of pre-submit names in the branch protection. The generic and Go builder pre-submit failed yet my 2 latest PRs were merged.

**Comment by ianlewis** [comment]
Hmm, we have the verify job for pre-submits as required, but it seems it fails open and allowed the merge because the verify jobs were skipped due to a previous job failing.

This is a bit annoying. We'll need to either add all pre-submit workflow jobs as required, or have a job in pre-submit workflows that always runs to produce the success/failure result instead of skipping.

**Comment by laurentsimon** [comment]
I'm unable to select the workflow's name as blocking (to have the entire workflow as required): it does not show up in the list of possible workflows.. which is really weird. Either the name is too long or the UX does not like `pre-submit` in the name.. or something else.

**Comment by ianlewis** [comment]
Yeah, it seems to only allow you to select "jobs" within the workflow. I previously set it to the verification jobs for each pre-submit (go and generic) but even then it seems to allow merging if a dependent job fails and the required one is skipped as a result :-/
