### ISSUE TITLE
[bug]  slsa-goreleaser action fails on "Create and sign provenance"

### ISSUE THREAD

**Issue by gorsat** [slsa-framework/slsa-github-generator#823]
I'm manually running a go-ossf-slsa3-publish.yml action in a private repo by pushing the "Run workflow" button on the actions page.
It fails on the step "Create and sign provenance"

Output from the failure:
```
>Run set -euo pipefail
provenance generator is slsa-builder-go-linux-amd64
getting entrypoint: getting workflow run: GET https://api.github.com/repos/gorsat/project_root/actions/runs/3011826089: (https://api.github.com/repos/gorsat/idco/actions/runs/3011826089:): 403 Resource not accessible by integration []
```
The only thing that is even slightly noteworthy about my config is that the file I'm building (yes, it's just one file) is in a subdir of the project root, so I have this in my .slsa-goreleaser.yml:
```
main: my-file.go
dir: ./my-sub-dir
```
In addition, I've commented out some of the lines marked "optional" in this file. 

But the error message looks like an authorization issue. So I'm wondering if the repo being private has something to do with it.

**Comment by ianlewis** [comment]
@gorsat Thanks for submitting the issue! I believe you're right and it is caused by the repo being private. In the Go workflow we aren't requesting the `actions: read` scope for the step where we are detecting the workflows environment.

https://github.com/slsa-framework/slsa-github-generator/blob/11f701ad156cb8616ed5f5a444f1da6e2b77ed24/.github/workflows/builder_go_slsa3.yml#L78-L79

Unfortunately, We will need to update the workflow and create another release for this to work with private repos.

In the meantime you can give the generic generator starter workflow a try. This one *should* work as we request the right permissions.
https://github.com/gorsat/reponame/actions/new?category=none&query=slsa

**Comment by laurentsimon** [comment]
One thing to know: the certificate with your repository name is uploaded to a transparency log for audit purposes. So by using this builder, you are revealing the name of your private repository.

Is that OK with you?

Let's add a disclaimer in the README to make this more explicit.

**Comment by gorsat** [comment]
Thanks for the heads-up. Yes, that's okay for me, but, yeah, a disclaimer would be great, especially for businesses.

**Comment by laurentsimon** [comment]
OK. So I propose

1. We amend the documentation
2. We add a `private-repository: true` option. At runtime we will check if the repo is private. If it is, we we only proceed if the option is set. Otherwise we will fail.

Wdut?

**Comment by gorsat** [comment]
I like it.
